name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Publish to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.DOCKER_USER }}" --password-stdin
        docker build -t ${{ secrets.DOCKER_USER }}/localstack-ui:latest .
        docker push ${{ secrets.DOCKER_USER }}/localstack-ui:latest
